// Этот файл генерируется автоматически в scripts/generate-svg-sprite.js
// Не редактируйте его вручную.

export const iconNames = [
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "basket",
  "check",
  "close",
  "compare",
  "delete",
  "delivery",
  "discount",
  "edit",
  "ellipsis",
  "eye-closed",
  "eye",
  "filter",
  "fire",
  "glasses",
  "lens-properties-adaptation-to-bright",
  "lens-properties-aesthetic-2",
  "lens-properties-aesthetic",
  "lens-properties-antireflex",
  "lens-properties-basic",
  "lens-properties-blocking",
  "lens-properties-blue-filtering",
  "lens-properties-blue-radiation",
  "lens-properties-brightness",
  "lens-properties-cheaper",
  "lens-properties-day-and-night",
  "lens-properties-fashionable",
  "lens-properties-for-driving",
  "lens-properties-fragile",
  "lens-properties-heavy",
  "lens-properties-lungs",
  "lens-properties-mirror-shades",
  "lens-properties-mirrored",
  "lens-properties-optimized",
  "lens-properties-prescription",
  "lens-properties-reflective",
  "lens-properties-shockproof",
  "lens-properties-strength-and-protection",
  "lens-properties-thin",
  "like-filled",
  "like",
  "long-arrow-left",
  "long-arrow-right",
  "menu",
  "minus",
  "pin-filled",
  "pin",
  "plus",
  "search",
  "social-instagram",
  "social-telegram",
  "social-vk",
  "tooltip",
  "user",
] as const

export type IconName = (typeof iconNames)[number]
